import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/app/globals.css";

const geistSans = localFont({
	// src: "@/app/fonts/GeistVF.woff",
	src: "../fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	// src: "@/app/fonts/GeistMonoVF.woff",
	src: "../fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});
const facultyGlyphic = localFont({
	// src: "@/app/fonts/FacultyGlyphic-Regular.ttf",
	src: "../fonts/FacultyGlyphic-Regular.ttf",
	variable: "--font-faculty-glyphic",
});

export const metadata: Metadata = {
	title: "Shreyansh - Developer Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
			// className={`${geistSans.variable} ${geistMono.variable} ${facultyGlyphic.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
